"""adding password hashed

Revision ID: c24d508754c1
Revises: d7d17ba55ec4
Create Date: 2025-03-11 13:09:07.631802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24d508754c1'
down_revision: Union[str, None] = 'd7d17ba55ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hashed', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hashed')
    # ### end Alembic commands ###
